### ISSUE TITLE
Test case MPC5748G flash ... GDB not starting issue

### ISSUE THREAD

**Issue by 192933488S** [jed-frey/opensda_flasher#1]
Hello Jed !
Thanks for this nice tool, but can you help with this issue?

## Precondition:

SW:

- Latest S32DS PPC
- Using MSYS2 (can recommend, no big installations like cygwin)
- Installed _python_ with _pacman_, then _pip_ and setuptools with the following command `curl https://bootstrap.pypa.io/get-pip.py | python`
- Cloned the repo, installed the script

HW:
- MPC5748G-DEVKIT

## Test case: 

$ osf --config mpc5748g.ini flash /c/dev/bin/z4_demo1_Z4_0.elf

(Also tested $ osf --config mpc5748g.ini flash C:/NXP/workspaceS32DS.Power12/z4_demo1_Z4_0.elf)

with MPC5748G adapted *.ini

## Expected result: 

Launch of GDB and automatic flash, LED on.

## Actual result:

GDB not starting, not flashed

```
$ osf --config mpc5748g.ini flash /c/dev/bin/z4_demo1_Z4_0.elf
Waiting for GDB servers to complete startup ...... Done
DEBUG: /tmp/gdb_abql6b0s.txt
Waiting for GDB client to flash ...... Done
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pexpect-4.2.1-py3.6.egg/pexpect/expect.py", line 97, in expect_loop
    return self.timeout()
  File "/usr/lib/python3.6/site-packages/pexpect-4.2.1-py3.6.egg/pexpect/expect.py", line 70, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x6fffe362358>
searcher: searcher_re:
    0: EOF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/osf", line 11, in <module>
    load_entry_point('opensda-flasher==0.2.0', 'console_scripts', 'osf')()
  File "/usr/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/opensda_flasher-0.2.0-py3.6.egg/opensda_flasher/cli.py", line 76, in flash
    c.flash(elfs)
  File "/usr/lib/python3.6/site-packages/opensda_flasher-0.2.0-py3.6.egg/opensda_flasher/client.py", line 95, in flash
    print(self.process.err)
  File "/usr/lib/python3.6/site-packages/delegator.py-0.0.13-py3.6.egg/delegator.py", line 110, in err
  File "/usr/lib/python3.6/site-packages/delegator.py-0.0.13-py3.6.egg/delegator.py", line 80, in _pexpect_out
  File "/usr/lib/python3.6/site-packages/pexpect-4.2.1-py3.6.egg/pexpect/spawnbase.py", line 413, in read
    self.expect(self.delimiter)
  File "/usr/lib/python3.6/site-packages/pexpect-4.2.1-py3.6.egg/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/usr/lib/python3.6/site-packages/pexpect-4.2.1-py3.6.egg/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/lib/python3.6/site-packages/pexpect-4.2.1-py3.6.egg/pexpect/expect.py", line 107, in expect_loop
    return self.timeout(e)
  File "/usr/lib/python3.6/site-packages/pexpect-4.2.1-py3.6.egg/pexpect/expect.py", line 70, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x6fffe362358>
searcher: searcher_re:
    0: EOF
<pexpect.popen_spawn.PopenSpawn object at 0x6fffe362358>
searcher: searcher_re:
    0: EOF


```

Init:

```
; MPC5748G init.

; S32 Settings.
[S32]
root = C:\NXP\S32DS_Power_v1.2

; Debug Server Settings.
[SERVER]
plugin = com.pemicro.debug.gdbjtag.ppc_1.6.9.201706282002
exe = pegdbserver_power_console.exe
device = MPC5748G
port = USB3
speed = 5000
serverport = 7224
platform = win32

; GDB CLient Settings.
[CLIENT]
platform = powerpc-eabivle-4_9
exe = powerpc-eabivle-gdb.exe

```
## Comments

How do you identify the USB port? I'm used to the COM ports with regards to OpenSDA. Board is connected to COM3 (btw, I found connecting to USB3.0 ports fires the board much quicker than 2.0)

Tested **port = USB1** and **port = USB3**, output same.

"Waiting for GDB client to flash ...... Done" There is a timeout of circa 5 seconds.

```
$ osf --config mpc5748g.ini flash
Traceback (most recent call last):
  File "/usr/bin/osf", line 11, in <module>
    load_entry_point('opensda-flasher==0.2.0', 'console_scripts', 'osf')()
  File "/usr/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/opensda_flasher-0.2.0-py3.6.egg/opensda_flasher/cli.py", line 55, in flash
    raise(Exception("No elf(s) specified in call or config file"))
Exception: No elf(s) specified in call or config file

```

**Comment by dapperfu** [comment]
The 48G, on account of having more cores, takes longer to reset. It was reaching the internal default timeout. Try updating from master and trying again.

I also added a folder with 'Golden Binaries' from the ADC Example demos. I tested all 3 on both of my development boards. If your binaries don't work try them.

The 'port' is PE Debugger's own internal numbering/naming. I added an osf command to show which boards are connected:

    > osf ports
    Command line arguments: -showhardware
    -INTERFACE=OPENSDA        -PORT=9CD0CE70                 ; USB1 : OpenSDA (9CD0CE70)[PortNum=181]
    -INTERFACE=OPENSDA        -PORT=USB1                     ; USB1 : OpenSDA (9CD0CE70)[PortNum=181][DUPLICATE]

The ```USB#``` change depending on order. The other one is based on serial(?).

**Comment by 192933488S** [comment]
Jed, I re-installed, but similar issue persists. Also, ports command shows empty output. Could you include -v for version to the app? 

(Assumption: Reinstalled with initial installation command: python setup.py install)

`$ osf ports

`

**Comment by dapperfu** [comment]
It'll probably be next week before I can properly dig into this.

1. Can you post you post the contents of ```build_version.txt``` from your ```pegdbserver_power_console.exe``` folder?

These are all the versions I have:
```
S32_Power_v1.1\eclipse\plugins\com.pemicro.debug.gdbjtag.ppc_1.3.3.201605241936\win32\pegdbserver_power_console.exe
S32DS_Power_v1.2\eclipse\plugins\com.pemicro.debug.gdbjtag.ppc_1.6.7.201706090048\win32\pegdbserver_power_console.exe
S32DS_Power_v1.2\eclipse\plugins\com.pemicro.debug.gdbjtag.ppc_1.6.9.201706282002\win32\pegdbserver_power_console.exe
```

Find the version that matches the version in the .ini:

For example ```plugin = com.pemicro.debug.gdbjtag.ppc_1.6.9.201706282002```:

Has this build_version:

    P&E DLL Version: v644
    P&E Build Date: 170628

2. Can you open a cmd console in that directory and post the output of ```pegdbserver_power_console.exe -showhardware```

This is the output of my two devboards.
![](https://i.imgur.com/5FyUVgk.png)

First let us diagnose if ```pegdbserver_power_console``` is seeing everything. The Python is just a wrapper on top of that.

3. > Could you include -v for version to the app?

  I will work on the UI a bit more and add some more intermediate debugging steps.

**Comment by 192933488S** [comment]
Thanks for quick feedback.

C:\NXP\S32DS_Power_v1.2\eclipse\plugins\com.pemicro.debug.gdbjtag.ppc_1.6.9.201706282002

`build_version.txt`

P&E DLL Version: v644
P&E Build Date: 170628

```
$ ./pegdbserver_power_console.exe -showhardware

P&E GDB Server for Power devices, Version 6.44.00.00
Copyright 2014, P&E Microcomputer Systems Inc, All rights reserved

Loading library C:\NXP\S32DS_Power_v1.2\eclipse\plugins\com.pemicro.debug.gdbjtag.ppc_1.6.9.201706282002\win32\gdi\unit_ngs_ppcnexus_internal.dll ... Done.

Command line arguments: -showhardware
-INTERFACE=OPENSDA        -PORT=41401E08                 ; USB1 : OpenSDA (41401E08)[PortNum=181]
-INTERFACE=OPENSDA        -PORT=USB1                     ; USB1 : OpenSDA (41401E08)[PortNum=181][DUPLICATE]

```

Cheers

**Comment by dapperfu** [comment]
Just a status update: 

I haven't gotten any time to work on it and some co-workers decided to set some things on fire at work so it'll probably be at least another week.

**Comment by 192933488S** [comment]
Update from my side:

Switched shell from MSYS2 to [STL's MinGW](https://nuwen.net/mingw.html) and this looks truly good now:


```
C:\dev\github\opensda_flasher\Golden_Binaries>osf -c=mpc5748g.ini flash ./z4_demo1_Z4_0.elf
Waiting for GDB servers to complete startup ...... Done
DEBUG: C:\Users\ludwi\AppData\Local\Temp\gdb_nae9umin.txt
Waiting for GDB client to flash ...... Done
GNU gdb (GDB) 7.8.2
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=i686-mingw32 --target=powerpc-eabivle".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
0x01000000 in ?? ()
Command Executed successfully: preserve1 0
The target architecture is assumed to be powerpc:vle
Loading section .startup, size 0x246 lma 0x40000000
Loading section .core_exceptions_table, size 0xf4 lma 0x40001000
Loading section .intc_vector_table, size 0xbc8 lma 0x40002000
Loading section .text, size 0x230 lma 0x40002bd0
Start address 0x40000000, load size 4402
Transfer rate: 2 KB/sec, 733 bytes/write.
Command Executed successfully: _reset
A debugging session is active.

        Inferior 1 [Remote target] will be detached.

Quit anyway? (y or n) [answered Y; input not from terminal]


C:\dev\github\opensda_flasher\Golden_Binaries>
```

LED is ON.

**Comment by dapperfu** [comment]
Excellent. That's definitely one that would have taken a while to find.
